### ISSUE TITLE
Validate checkpoint simulation

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#1189]
We have prototype of checkpoint simulation. We need to be confident that it works before trying to integrate it into the scheduler

- Test that making a checkpoint makes it independent from the original engine
- Test that restarting from a checkpoint produces the same results as re-simulating from the beginning
- Any other edge cases we come up with

Branch: `prototype/duplicatable-sim-engine`

```[tasklist]
### Tasks
- [x] Design a test procedure to check that it works
- [ ] Fix any bugs that come out of testing
- [x] Try on clipper model to see if memory explodes
```

**Comment by dandelany** [comment]
@mattdailis and @adrienmaillard met about this on Slack, here are Matt's notes:

Goal: Determine as soon as possible whether this will work
Tasks:
- Unit testing
- See if it is feasible on the clipper model
	- Visualize memory usage on a realistic plan (e.g. 6 years)
	- Set breakpoints in simulation
### Memory observation procedure:
1. Check out and build Aerie on 1.14.0 with added memory logging
2. Load recent Clipper mission model into Aerie
3. Create 6 year plan with some activities
	1. Randomly? Or use a plan from Megan
4. Just run a normal simulation and observe memory usage
5. Check out and build Aerie using the duplicatable sim engine branch
6. Just run a normal simulation with no checkpoints and observe memory usage
7. Duplicate the simulation engine before each activity start
8. Observe memory using Java API and logging
	1. `Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()`

Questions to answer:
- How many checkpoints before we run out of memory?
- Approximately how big is a single checkpoint? Does this vary?
In order to test this, we need access to the *old* engine as well as the *new* engine in the same program
### Action items
- [ ] Preserve ability to run old simulation engine and old threaded tasks for testing purposes
	- [ ] Allow for selecting which engine to run through environment variable?

**Comment by dandelany** [comment]
Notes from sprint planning meeting today:
* @adrienmaillard will finalize reviewing the current prototype & testing with the Clipper model
* some small interface improvements are planned by @mattdailis in the current prototype
* our current plan is to PR/merge an updated version of the prototype branch but not yet enabled in the scheduler

**Comment by adrienmaillard** [comment]
Tests are on the `duplicatable-sim-engine-test-clipper`.
