### ISSUE TITLE
JVM-based procedural scheduler prototype

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#1248]
Create a demo-able prototype for procedural scheduling, where the user code is written in Java (or Kotlin!). It will probably be similar to Adrien's external scheduler in a lot of ways. The main differences for the demo will be a more streamlined profiles/activities interface and a revised goal interface.

```[tasklist]
### Tasks
- [ ] meet with @adrienmaillard to see what parts of the external scheduler can be reused
- [ ] basic timeline objects (profiles, activities, conflicts)
- [ ] connect to database
- [ ] revisit interface (simulation control, should be able to return conflicts or directives)
```

Other tasks, such as using the mission model's value mappers, feature-complete profile operations, integration into the schedule action, and providing a template build.gradle file for compiling multiple jars are not included in the prototype.

**Comment by JoelCourtney** [comment]
will replace with smaller tickets
