### ISSUE TITLE
Procedural scheduling library MVP

### ISSUE THREAD

**Issue by JoelCourtney** [NASA-AMMOS/aerie#1301]
```[tasklist]
### Tasks
- [ ] goal helpers (coexistence, recurrence, etc)
- [ ] conflict type
- [ ] goal interface
- [ ] simulation control facade
- [ ] scheduling condition interop
```
