### ISSUE TITLE
Merge the Aerie Databases

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1311]
Following another revisit to the topic #494, we have decided to merge the databases.

Completion of this ticket will involve:
```[tasklist]
### Tasks
- [x] Combining the 4 DBs into 1 DB with many schemas. Current prediction is 1 per service (Merlin, Scheduler, Sequencing, UI), plus 1 for `migrations`, and either 1 `metadata` schema or 1 `tag` and 1 `permissions` schema.
- [x] Update the db initialization process
- [x] Make 1 postgres user per Aerie Service. Define DB permissions
- [x] Update the Hasura Metadata to preserve the current API
- [x] Create a script to perform the merge on existing venues (not sure if this would be a `.sql` or a `.sh`)
- [x] Update the `aerie_db_migrations` python helper script (low priority)
- [x] Document that this migration is up-only, and archive and clean out the old migrations
- [x] Update the backend DB writes
```
