### ISSUE TITLE
Aerie Dev Deployment Improvements

### ISSUE THREAD

**Issue by skovati** [NASA-AMMOS/aerie#987]
The existing [development deployment](https://aerie-dev.jpl.nasa.gov) is essentially a shell script running in a cronjob which tends to be both brittle and opaque. The AMMOS in the Cloud team has been developing a more robust [ECS](https://aws.amazon.com/ecs/)-based deployment using [terraform](https://www.terraform.io). This meta ticket will track the progress in integrating this work into the existing Aerie developer environment.

```[tasklist]
### Tasks
- [ ] Standup Aerie terraform deployment (S3 state bucket)
- [ ] Bring infra-as-code into NASA-AMMOS namespace
- [ ] Convert to Continuous Deployment (λ function cron updating ECS tasks)
- [ ] Automate database migrations (λ function running `aerie_db_migration.py`
- [ ] Automate database backups (λ function running pgdump)
- [ ] Update deployment status on GH
```

**Comment by dandelany** [comment]
Another thing we talked about recently: aerie-dev should alert us somehow if migrations fail
